"""BunqShield — Pre-computed demo scenarios. Zero external dependencies."""
import base64
import io
import math
import uuid

from schemas import BoundingBox, CVMethodResult, FraudReport, PaymentSummary, ViTResult


def _make_heatmap_base64(hot_region: str) -> str:
    """Generate a simple colored heatmap PNG without matplotlib."""
    try:
        from PIL import Image
        import numpy as np

        w, h = 224, 224
        data = np.zeros((h, w, 3), dtype=np.uint8)

        # Cool blue background
        data[:, :, 2] = 40

        if hot_region == "amount":
            # Bottom-right quadrant hot
            data[140:, 112:, 0] = 220
            data[140:, 112:, 1] = 30
            data[140:, 112:, 2] = 30
        elif hot_region == "header":
            # Top strip hot
            data[:45, :, 0] = 220
            data[:45, :, 1] = 30
            data[:45, :, 2] = 30
        # else: all cool (clean)

        img = Image.fromarray(data, "RGB")
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return base64.b64encode(buf.getvalue()).decode()
    except Exception:
        return ""


def _flat_patches(hot_region: str) -> list[float]:
    """196 patch scores (14×14) with hot region elevated."""
    scores = [0.05] * 196
    if hot_region == "amount":
        for row in range(9, 14):
            for col in range(7, 14):
                scores[row * 14 + col] = 0.85
    elif hot_region == "header":
        for col in range(14):
            scores[col] = 0.80
            scores[14 + col] = 0.75
    return scores


def _attention_map(patch_scores: list[float]) -> list[list[float]]:
    return [patch_scores[i * 14 : (i + 1) * 14] for i in range(14)]


# --- Scenario: clean ---
_clean_patches = _flat_patches("none")
CLEAN_REPORT = FraudReport(
    job_id="demo-clean-001",
    status="complete",
    fused_score=8.0,
    risk_level="clean",
    cv_results=[
        CVMethodResult(method="ela", score=5.0, details="Uniform JPEG compression artifacts consistent with original document generation. No localized re-compression detected."),
        CVMethodResult(method="copy_move", score=0.0, details="No self-similar regions found. ORB feature matching returned zero suspicious clusters."),
        CVMethodResult(method="noise_inconsistency", score=8.0, details="Noise distribution is homogeneous across all image blocks. MAD variance within normal range."),
        CVMethodResult(method="font_consistency", score=6.0, details="Stroke width variance is consistent throughout all text regions. No mixed font signatures detected."),
        CVMethodResult(method="metadata_forensics", score=0.0, details="EXIF metadata is clean. No editing tool signatures detected in binary header."),
        CVMethodResult(method="edge_coherence", score=12.0, details="Edge gradient directions are coherent across all regions. No splicing boundaries detected."),
    ],
    vit_result=ViTResult(
        vit_score=9.0,
        patch_scores=_clean_patches,
        attention_map=_attention_map(_clean_patches),
        heatmap_base64=_make_heatmap_base64("none"),
    ),
    agent_reasoning="Invoice metadata is consistent with authentic AWS billing. No pixel-level anomalies detected across all six forensic methods. ELA analysis shows uniform compression artifacts consistent with original document generation. Payment approved automatically.",
    agent_decision="approve",
    processing_time_ms=42.0,
    demo_mode=True,
)

# --- Scenario: tampered_amount ---
_tampered_patches = _flat_patches("amount")
TAMPERED_REPORT = FraudReport(
    job_id="demo-tampered-001",
    status="complete",
    fused_score=78.0,
    risk_level="critical",
    cv_results=[
        CVMethodResult(method="ela", score=85.0, details="Severe JPEG re-compression artifacts localized to invoice total field. Amplified ELA map shows 3.2× above-baseline intensity in bottom-right quadrant.", suspicious_regions=[BoundingBox(x=320, y=580, w=180, h=45)]),
        CVMethodResult(method="copy_move", score=45.0, details="3 suspicious copy-move clusters detected near amount field. ORB matching found 12 self-similar patch pairs within 50px proximity.", suspicious_regions=[BoundingBox(x=310, y=570, w=200, h=60)]),
        CVMethodResult(method="noise_inconsistency", score=72.0, details="Noise MAD in amount region is 4.1× higher than document median. Block-level analysis confirms localized noise injection.", suspicious_regions=[BoundingBox(x=315, y=575, w=190, h=50)]),
        CVMethodResult(method="font_consistency", score=68.0, details="Stroke width in amount field deviates 2.8 standard deviations from document font baseline. Possible font substitution detected."),
        CVMethodResult(method="metadata_forensics", score=90.0, details="Adobe Photoshop CC 2024 signature detected in binary header. Document claims to be generated by AWS billing system — inconsistency flagged."),
        CVMethodResult(method="edge_coherence", score=55.0, details="Edge direction entropy spike at coordinates (320, 580). Boundary artifact consistent with pasted region.", suspicious_regions=[BoundingBox(x=318, y=578, w=185, h=48)]),
    ],
    vit_result=ViTResult(
        vit_score=82.0,
        patch_scores=_tampered_patches,
        attention_map=_attention_map(_tampered_patches),
        heatmap_base64=_make_heatmap_base64("amount"),
    ),
    agent_reasoning="Critical fraud indicators detected. ELA analysis reveals severe JPEG re-compression artifacts localized to the invoice total field, strongly suggesting pixel-level editing. Metadata forensics detected Adobe Photoshop signature inconsistent with the claimed document origin. The ViT model assigns maximum suspicion scores to patches covering the amount region. Payment blocked immediately.",
    agent_decision="block",
    processing_time_ms=38.0,
    demo_mode=True,
)

# --- Scenario: logo_replacement ---
_logo_patches = _flat_patches("header")
LOGO_REPORT = FraudReport(
    job_id="demo-logo-001",
    status="complete",
    fused_score=62.0,
    risk_level="high",
    cv_results=[
        CVMethodResult(method="ela", score=55.0, details="Elevated ELA response in document header region. Re-compression boundary visible at y=42px, consistent with image splicing.", suspicious_regions=[BoundingBox(x=0, y=0, w=400, h=45)]),
        CVMethodResult(method="copy_move", score=70.0, details="Logo region shows 7 copy-move clusters. Source patches match external image characteristics rather than document body.", suspicious_regions=[BoundingBox(x=10, y=5, w=180, h=38)]),
        CVMethodResult(method="noise_inconsistency", score=48.0, details="Noise profile in header differs from document body. Header noise variance is 2.1× lower, suggesting different source image."),
        CVMethodResult(method="font_consistency", score=35.0, details="Font metrics in header text region are consistent with document body. No font substitution detected."),
        CVMethodResult(method="metadata_forensics", score=75.0, details="GIMP 2.10 editing signature detected. Creation timestamp predates the invoice date by 3 days — inconsistency flagged."),
        CVMethodResult(method="edge_coherence", score=60.0, details="Sharp edge discontinuity at header/body boundary (y=44px). Gradient direction histogram shows bimodal distribution inconsistent with natural document.", suspicious_regions=[BoundingBox(x=0, y=40, w=600, h=8)]),
    ],
    vit_result=ViTResult(
        vit_score=65.0,
        patch_scores=_logo_patches,
        attention_map=_attention_map(_logo_patches),
        heatmap_base64=_make_heatmap_base64("header"),
    ),
    agent_reasoning="High-confidence fraud indicators in the document header. Copy-move detection identified self-similar regions consistent with logo splicing. Metadata forensics detected GIMP editing signatures. The ViT cross-attention mechanism highlights the header region as the primary anomaly. Payment blocked pending manual review.",
    agent_decision="block",
    processing_time_ms=41.0,
    demo_mode=True,
)

DEMO_SCENARIOS: dict[str, FraudReport] = {
    "clean": CLEAN_REPORT,
    "tampered_amount": TAMPERED_REPORT,
    "logo_replacement": LOGO_REPORT,
}

DEMO_PAYMENTS: list[PaymentSummary] = [
    PaymentSummary(payment_id="pay-001", amount=1247.50, currency="EUR", counterparty="AWS EMEA SARL", description="AWS Invoice INV-2024-001247", status="approved", fraud_score=8.0, created_at="2024-01-15T10:23:00Z"),
    PaymentSummary(payment_id="pay-002", amount=8500.00, currency="EUR", counterparty="Office Supplies Ltd", description="Invoice #OS-2024-0892", status="blocked", fraud_score=78.0, created_at="2024-01-14T14:05:00Z"),
    PaymentSummary(payment_id="pay-003", amount=3200.00, currency="EUR", counterparty="TechCorp BV", description="Software License Q1 2024", status="flagged", fraud_score=62.0, created_at="2024-01-13T09:17:00Z"),
    PaymentSummary(payment_id="pay-004", amount=450.00, currency="EUR", counterparty="Freelancer Design", description="Logo design project", status="pending", fraud_score=None, created_at="2024-01-12T16:44:00Z"),
    PaymentSummary(payment_id="pay-005", amount=2100.00, currency="EUR", counterparty="Cloud Services GmbH", description="Monthly hosting invoice", status="approved", fraud_score=12.0, created_at="2024-01-11T11:30:00Z"),
]
